<?php

declare(strict_types=1);

namespace App\Libraries\MyCrud\Generators;

/**
 * Generates read-only MCP tools for belongsTo and hasMany.
 *
 * Tutte le letture passano direttamente dal Model generato:
 * - belongsTo: getDetail() + relationOptionById()
 * - hasMany: loadHasMany()
 */
final class McpRelationToolGenerator
{
    use GeneratorTrait;

    public function generate(array $config, bool $force = false): array
    {
        $mcp = (array) ($config['mcp'] ?? []);
        $caps = (array) ($mcp['capabilities'] ?? []);

        if (
            empty($mcp['enabled'])
            || empty($caps['relations'])
            || (string) ($config['architecture'] ?? '') !== 'full'
        ) {
            return [];
        }

        $table = (string) ($config['table'] ?? '');
        $studly = $this->studly($table);
        $class = $studly . 'RelationTools';
        $model = (string) ($config['classes']['model'] ?? ($studly . 'Model'));

        $methods = [];
        $toolNames = [];

        // belongsTo: only actual relations of the current table.
        foreach ((array) ($config['relations']['belongsTo'] ?? []) as $field => $relation) {
            $field = (string) $field;
            $parentTable = (string) ($relation['parentTable'] ?? '');
            if ($field === '' || $parentTable === '') {
                continue;
            }

            $methodSuffix = $this->studly($field);
            $toolName = $this->toolName('get_' . $table . '_' . $field);
            $toolNames[] = $toolName;

            $methods[] = <<<PHP
    /**
     * Returns the belongsTo {$parentTable} relation associated with {$table}.{$field}.
     *
     * Reads the {$table} record, retrieves the foreign-key value, and resolves the label
     * configured through the generated Model.
     *
     * @param string \$id Primary key of the {$table} record.
     *
     * @return array{
     *     field: string,
     *     parentTable: string,
     *     value: string|null,
     *     relation: array<string,mixed>|null
     * }
     */
    #[McpTool(
        name: '{$toolName}',
        title: 'Get {$parentTable} relation for {$table}.{$field}'
    )]
    public function get{$studly}{$methodSuffix}(string \$id): array
    {
        \$record = \$this->model->getDetail(\$id);
        if (!is_object(\$record)) {
            throw new \InvalidArgumentException('Record not found.');
        }
        \$foreignId = is_array(\$record)
            ? (\$record['{$field}'] ?? null)
            : (\$record->{$field} ?? null);

        if (\$foreignId === null || \$foreignId === '') {
            return [
                'field' => '{$field}',
                'parentTable' => '{$parentTable}',
                'value' => null,
                'relation' => null,
            ];
        }

        return [
            'field' => '{$field}',
            'parentTable' => '{$parentTable}',
            'value' => (string) \$foreignId,
            'relation' => \$this->model->relationOptionById('{$field}', \$foreignId),
        ];
    }

PHP;
        }

        // hasMany: solo pannelli/configurazioni effettivamente abilitati.
        foreach ((array) ($config['relationsConfig']['hasMany'] ?? []) as $relationKey => $relation) {
            if (empty($relation['enabled'])) {
                continue;
            }

            $relationKey = (string) $relationKey;
            $childTable = (string) ($relation['childTable'] ?? '');
            $foreignKey = (string) ($relation['foreignKey'] ?? '');
            if ($relationKey === '' || $childTable === '' || $foreignKey === '') {
                continue;
            }

            $methodSuffix = $this->studly($childTable . '_' . $foreignKey);
            $toolName = $this->toolName('list_' . $table . '_' . $childTable . '_by_' . $foreignKey);
            $toolNames[] = $toolName;

            $methods[] = <<<PHP
    /**
     * Returns the {$childTable} records related to the {$table} record.
     *
     * Uses the hasMany scaffold generated by the Model and preserves
     * the limit, count, and hasMore values defined by the relation configuration.
     *
     * @param string \$id Primary key of the {$table} record.
     *
     * @return array{
     *     relation: string,
     *     childTable: string,
     *     foreignKey: string,
     *     rows: array<int,mixed>,
     *     count: int,
     *     hasMore: bool
     * }
     */
    #[McpTool(
        name: '{$toolName}',
        title: 'List {$childTable} related to {$table}'
    )]
    public function list{$studly}{$methodSuffix}(string \$id): array
    {
        \$relations = \$this->model->loadHasMany(\$id);
        \$result = (array) (\$relations['{$relationKey}'] ?? []);

        return [
            'relation' => '{$relationKey}',
            'childTable' => '{$childTable}',
            'foreignKey' => '{$foreignKey}',
            'rows' => array_values((array) (\$result['rows'] ?? [])),
            'count' => (int) (\$result['count'] ?? 0),
            'hasMore' => !empty(\$result['hasMore']),
        ];
    }

PHP;
        }

        if ($methods === []) {
            return [];
        }

        $methodsCode = implode("\n", $methods);

        $content = <<<PHP
<?php

declare(strict_types=1);

namespace App\\Mcp\\Tools;

use App\\Models\\{$model};
use Mcp\\Capability\\Attribute\\McpTool;

/**
 * Read-only relation tools generated by myCrudCI4 for {$table}.
 */
final class {$class}
{
    public function __construct(private readonly {$model} \$model = new {$model}())
    {
    }

{$methodsCode}}

PHP;

        return [
            'file' => $this->writeGenerated(
                'Generated/Mcp/Tools/' . $class . '.php',
                $content,
                $force
            ),
            'tools' => array_values(array_unique($toolNames)),
        ];
    }

    /** @return list<string> */
    public function toolNames(array $config): array
    {
        $mcp = (array) ($config['mcp'] ?? []);
        if (empty($mcp['enabled']) || empty($mcp['capabilities']['relations'])) {
            return [];
        }

        $table = (string) ($config['table'] ?? '');
        $names = [];

        foreach ((array) ($config['relations']['belongsTo'] ?? []) as $field => $relation) {
            if ((string) ($relation['parentTable'] ?? '') !== '') {
                $names[] = $this->toolName('get_' . $table . '_' . (string) $field);
            }
        }

        foreach ((array) ($config['relationsConfig']['hasMany'] ?? []) as $relation) {
            if (empty($relation['enabled'])) {
                continue;
            }

            $childTable = (string) ($relation['childTable'] ?? '');
            $foreignKey = (string) ($relation['foreignKey'] ?? '');
            if ($childTable !== '' && $foreignKey !== '') {
                $names[] = $this->toolName(
                    'list_' . $table . '_' . $childTable . '_by_' . $foreignKey
                );
            }
        }

        return array_values(array_unique($names));
    }

    private function toolName(string $value): string
    {
        $name = strtolower((string) preg_replace('/[^a-zA-Z0-9_.-]+/', '_', $value));

        return substr($name, 0, 128);
    }

    private function studly(string $value): string
    {
        $parts = preg_split('/[^a-zA-Z0-9]+/', $value) ?: [$value];

        $result = implode('', array_map(
            static fn (string $part): string => ucfirst(strtolower($part)),
            $parts
        ));

        return $result !== '' ? $result : 'Relation';
    }
}
