<?php

declare(strict_types=1);

namespace App\Mcp\Tools;

use App\Mcp\Resources\FilmMcpResource;
use App\Models\FilmModel;
use InvalidArgumentException;
use Mcp\Capability\Attribute\McpTool;

/**
 * MCP tools generated by myCrudCI4 for film.
 *
 * Read-only by design; MCP projection is independent from REST.
 */
final class FilmTools
{
    private const FILTERABLE_FIELDS = array (
  0 => 'film_id',
  1 => 'title',
  2 => 'language_id',
  3 => 'original_language_id',
);
    private const SORTABLE_FIELDS = array (
  0 => 'film_id',
  1 => 'title',
  2 => 'language_id',
  3 => 'original_language_id',
);

    public function __construct(private readonly FilmModel $model = new FilmModel())
    {
    }

    /**
     * Returns a paginated read-only list of film records.
     *
     * Filtering and sorting are restricted to static Tool-boundary whitelists.
     *
     * @param int         $page        Requested page, minimum 1.
     * @param int         $perPage     Records per page, minimum 1 and maximum 100.
     * @param string|null $filterField Filterable MCP field.
     * @param string|null $filterValue Filter value.
     * @param string|null $sort        Sortable MCP field.
     * @param string      $direction   Sort direction: asc or desc.
     *
     * @return array{
     *     data: array<int,array<string,mixed>>,
     *     meta: array<string,mixed>,
     *     links: array<string,mixed>
     * }
     */
    #[McpTool(
        name: 'list_film',
        title: 'List film'
    )]
    public function listFilm(
        int $page = 1,
        int $perPage = 25,
        ?string $filterField = null,
        ?string $filterValue = null,
        ?string $sort = null,
        string $direction = 'asc'
    ): array {
        $page = max(1, $page);
        $perPage = max(1, min(100, $perPage));

        $filterable = self::FILTERABLE_FIELDS;
        $sortable = self::SORTABLE_FIELDS;

        $query = [
            'page' => $page,
            'perPage' => $perPage,
            'direction' => strtolower($direction) === 'desc' ? 'desc' : 'asc',
        ];

        if ($filterField !== null && $filterField !== '') {
            if (!in_array($filterField, $filterable, true)) {
                throw new InvalidArgumentException(
                    'Filter not allowed. Available fields: ' . implode(', ', $filterable)
                );
            }
            $query['filter'] = [$filterField => (string) ($filterValue ?? '')];
        }

        if ($sort !== null && $sort !== '') {
            if (!in_array($sort, $sortable, true)) {
                throw new InvalidArgumentException(
                    'Sorting not allowed. Available fields: ' . implode(', ', $sortable)
                );
            }
            $query['sort'] = $sort;
        }

        $result = $this->model->apiList($query, $filterable, $sortable);

        return [
            'data' => FilmMcpResource::collection($result['rows']),
            'meta' => $result['meta'],
            'links' => $result['links'],
        ];
    }

    /**
     * Returns the read-only details of a film record.
     *
     * @param string $id Record primary key.
     *
     * @return array<string,mixed>
     */
    #[McpTool(
        name: 'get_film',
        title: 'Get film'
    )]
    public function getFilm(string $id): array
    {
        $record = $this->model->getDetail($id);
        if (!is_object($record)) {
            throw new InvalidArgumentException('Record not found.');
        }

        return FilmMcpResource::make($record);
    }
}
