<?php

declare(strict_types=1);

namespace App\Mcp\Tools;

use App\Models\StoreModel;
use Mcp\Capability\Attribute\McpTool;

/**
 * Read-only relation tools generated by myCrudCI4 for store.
 */
final class StoreRelationTools
{
    public function __construct(private readonly StoreModel $model = new StoreModel())
    {
    }

    /**
     * Returns the belongsTo address relation associated with store.address_id.
     *
     * Reads the store record, retrieves the foreign-key value, and resolves the label
     * configured through the generated Model.
     *
     * @param string $id Primary key of the store record.
     *
     * @return array{
     *     field: string,
     *     parentTable: string,
     *     value: string|null,
     *     relation: array<string,mixed>|null
     * }
     */
    #[McpTool(
        name: 'get_store_address_id',
        title: 'Get address relation for store.address_id'
    )]
    public function getStoreAddressId(string $id): array
    {
        $record = $this->model->getDetail($id);
        if (!is_object($record)) {
            throw new \InvalidArgumentException('Record not found.');
        }
        $foreignId = is_array($record)
            ? ($record['address_id'] ?? null)
            : ($record->address_id ?? null);

        if ($foreignId === null || $foreignId === '') {
            return [
                'field' => 'address_id',
                'parentTable' => 'address',
                'value' => null,
                'relation' => null,
            ];
        }

        return [
            'field' => 'address_id',
            'parentTable' => 'address',
            'value' => (string) $foreignId,
            'relation' => $this->model->relationOptionById('address_id', $foreignId),
        ];
    }

    /**
     * Returns the belongsTo staff relation associated with store.manager_staff_id.
     *
     * Reads the store record, retrieves the foreign-key value, and resolves the label
     * configured through the generated Model.
     *
     * @param string $id Primary key of the store record.
     *
     * @return array{
     *     field: string,
     *     parentTable: string,
     *     value: string|null,
     *     relation: array<string,mixed>|null
     * }
     */
    #[McpTool(
        name: 'get_store_manager_staff_id',
        title: 'Get staff relation for store.manager_staff_id'
    )]
    public function getStoreManagerStaffId(string $id): array
    {
        $record = $this->model->getDetail($id);
        if (!is_object($record)) {
            throw new \InvalidArgumentException('Record not found.');
        }
        $foreignId = is_array($record)
            ? ($record['manager_staff_id'] ?? null)
            : ($record->manager_staff_id ?? null);

        if ($foreignId === null || $foreignId === '') {
            return [
                'field' => 'manager_staff_id',
                'parentTable' => 'staff',
                'value' => null,
                'relation' => null,
            ];
        }

        return [
            'field' => 'manager_staff_id',
            'parentTable' => 'staff',
            'value' => (string) $foreignId,
            'relation' => $this->model->relationOptionById('manager_staff_id', $foreignId),
        ];
    }

    /**
     * Returns the customer records related to the store record.
     *
     * Uses the hasMany scaffold generated by the Model and preserves
     * the limit, count, and hasMore values defined by the relation configuration.
     *
     * @param string $id Primary key of the store record.
     *
     * @return array{
     *     relation: string,
     *     childTable: string,
     *     foreignKey: string,
     *     rows: array<int,mixed>,
     *     count: int,
     *     hasMore: bool
     * }
     */
    #[McpTool(
        name: 'list_store_customer_by_store_id',
        title: 'List customer related to store'
    )]
    public function listStoreCustomerStoreId(string $id): array
    {
        $relations = $this->model->loadHasMany($id);
        $result = (array) ($relations['customer__store_id'] ?? []);

        return [
            'relation' => 'customer__store_id',
            'childTable' => 'customer',
            'foreignKey' => 'store_id',
            'rows' => array_values((array) ($result['rows'] ?? [])),
            'count' => (int) ($result['count'] ?? 0),
            'hasMore' => !empty($result['hasMore']),
        ];
    }

    /**
     * Returns the inventory records related to the store record.
     *
     * Uses the hasMany scaffold generated by the Model and preserves
     * the limit, count, and hasMore values defined by the relation configuration.
     *
     * @param string $id Primary key of the store record.
     *
     * @return array{
     *     relation: string,
     *     childTable: string,
     *     foreignKey: string,
     *     rows: array<int,mixed>,
     *     count: int,
     *     hasMore: bool
     * }
     */
    #[McpTool(
        name: 'list_store_inventory_by_store_id',
        title: 'List inventory related to store'
    )]
    public function listStoreInventoryStoreId(string $id): array
    {
        $relations = $this->model->loadHasMany($id);
        $result = (array) ($relations['inventory__store_id'] ?? []);

        return [
            'relation' => 'inventory__store_id',
            'childTable' => 'inventory',
            'foreignKey' => 'store_id',
            'rows' => array_values((array) ($result['rows'] ?? [])),
            'count' => (int) ($result['count'] ?? 0),
            'hasMore' => !empty($result['hasMore']),
        ];
    }

    /**
     * Returns the staff records related to the store record.
     *
     * Uses the hasMany scaffold generated by the Model and preserves
     * the limit, count, and hasMore values defined by the relation configuration.
     *
     * @param string $id Primary key of the store record.
     *
     * @return array{
     *     relation: string,
     *     childTable: string,
     *     foreignKey: string,
     *     rows: array<int,mixed>,
     *     count: int,
     *     hasMore: bool
     * }
     */
    #[McpTool(
        name: 'list_store_staff_by_store_id',
        title: 'List staff related to store'
    )]
    public function listStoreStaffStoreId(string $id): array
    {
        $relations = $this->model->loadHasMany($id);
        $result = (array) ($relations['staff__store_id'] ?? []);

        return [
            'relation' => 'staff__store_id',
            'childTable' => 'staff',
            'foreignKey' => 'store_id',
            'rows' => array_values((array) ($result['rows'] ?? [])),
            'count' => (int) ($result['count'] ?? 0),
            'hasMore' => !empty($result['hasMore']),
        ];
    }
}
