openapi: 3.0.3
info:
  title: 'emails API'
  version: 1.0.0
paths:
  /api/v1/emails:
    get:
      summary: 'Elenco emails'
      parameters:
        - name: page
          in: query
          schema: { type: integer, minimum: 1 }
        - name: perPage
          in: query
          schema: { type: integer, minimum: 1, maximum: 100 }
        - name: 'filter[id]'
          in: query
          schema:
            type: integer
            format: int32
        - name: 'filter[direction]'
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema: { type: string, enum: ['id', 'direction'] }
        - name: direction
          in: query
          schema: { type: string, enum: [asc, desc] }
      responses:
        '200':
          description: Elenco paginato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailsListResponse'
    post:
      summary: Crea record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailsCreate'
      responses:
        '201':
          description: Record creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailsCreatedResponse'
        '422': { description: Errore di validazione }
  /api/v1/emails/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      summary: Dettaglio record
      responses:
        '200':
          description: Record trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/EmailsRead'
        '404': { description: Record non trovato }
    put:
      summary: Aggiornamento completo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailsUpdate'
      responses:
        '200': { description: Record aggiornato }
        '422': { description: Errore di validazione }
    patch:
      summary: Aggiornamento parziale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailsPatch'
      responses:
        '200': { description: Record aggiornato }
        '422': { description: Errore di validazione }
    delete:
      summary: Elimina record
      responses:
        '204': { description: Record eliminato }
components:
  schemas:
    EmailsRead:
      type: object
      properties:
        'id':
          type: integer
          format: int32
        'direction':
          type: string
          maxLength: 3
        'uid':
          type: string
          maxLength: 255
        'message_id':
          type: string
          nullable: true
          maxLength: 255
        'in_reply_to':
          type: string
          nullable: true
          maxLength: 255
        'refs':
          type: string
          nullable: true
          maxLength: 65535
        'email_from':
          type: string
          nullable: true
          maxLength: 255
        'thread_id':
          type: string
          nullable: true
          maxLength: 100
        'thread_status':
          type: string
          nullable: true
          maxLength: 6
        'subject':
          type: string
          nullable: true
          maxLength: 65535
        'body':
          type: string
          nullable: true
          maxLength: 65535
        'category':
          type: string
          nullable: true
          maxLength: 50
        'language':
          type: string
          nullable: true
          maxLength: 50
        'reply':
          type: string
          nullable: true
          maxLength: 65535
        'attachments':
          type: string
          nullable: true
          maxLength: 65535
        'replied':
          type: boolean
          nullable: true
    EmailsCreate:
      type: object
      required:
        - 'uid'
      properties:
        'direction':
          type: string
          maxLength: 3
        'uid':
          type: string
          maxLength: 255
        'message_id':
          type: string
          nullable: true
          maxLength: 255
        'in_reply_to':
          type: string
          nullable: true
          maxLength: 255
        'refs':
          type: string
          nullable: true
          maxLength: 65535
        'email_from':
          type: string
          nullable: true
          maxLength: 255
        'thread_id':
          type: string
          nullable: true
          maxLength: 100
        'thread_status':
          type: string
          nullable: true
          maxLength: 6
        'subject':
          type: string
          nullable: true
          maxLength: 65535
        'body':
          type: string
          nullable: true
          maxLength: 65535
        'category':
          type: string
          nullable: true
          maxLength: 50
        'language':
          type: string
          nullable: true
          maxLength: 50
        'reply':
          type: string
          nullable: true
          maxLength: 65535
        'attachments':
          type: string
          nullable: true
          maxLength: 65535
        'replied':
          type: boolean
          nullable: true
    EmailsUpdate:
      type: object
      required:
        - 'uid'
      properties:
        'direction':
          type: string
          maxLength: 3
        'uid':
          type: string
          maxLength: 255
        'message_id':
          type: string
          nullable: true
          maxLength: 255
        'in_reply_to':
          type: string
          nullable: true
          maxLength: 255
        'refs':
          type: string
          nullable: true
          maxLength: 65535
        'email_from':
          type: string
          nullable: true
          maxLength: 255
        'thread_id':
          type: string
          nullable: true
          maxLength: 100
        'thread_status':
          type: string
          nullable: true
          maxLength: 6
        'subject':
          type: string
          nullable: true
          maxLength: 65535
        'body':
          type: string
          nullable: true
          maxLength: 65535
        'category':
          type: string
          nullable: true
          maxLength: 50
        'language':
          type: string
          nullable: true
          maxLength: 50
        'reply':
          type: string
          nullable: true
          maxLength: 65535
        'attachments':
          type: string
          nullable: true
          maxLength: 65535
        'replied':
          type: boolean
          nullable: true
    EmailsPatch:
      type: object
      properties:
        'direction':
          type: string
          maxLength: 3
        'uid':
          type: string
          maxLength: 255
        'message_id':
          type: string
          nullable: true
          maxLength: 255
        'in_reply_to':
          type: string
          nullable: true
          maxLength: 255
        'refs':
          type: string
          nullable: true
          maxLength: 65535
        'email_from':
          type: string
          nullable: true
          maxLength: 255
        'thread_id':
          type: string
          nullable: true
          maxLength: 100
        'thread_status':
          type: string
          nullable: true
          maxLength: 6
        'subject':
          type: string
          nullable: true
          maxLength: 65535
        'body':
          type: string
          nullable: true
          maxLength: 65535
        'category':
          type: string
          nullable: true
          maxLength: 50
        'language':
          type: string
          nullable: true
          maxLength: 50
        'reply':
          type: string
          nullable: true
          maxLength: 65535
        'attachments':
          type: string
          nullable: true
          maxLength: 65535
        'replied':
          type: boolean
          nullable: true
    EmailsListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EmailsRead'
        meta: { type: object }
        links: { type: object }
    EmailsCreatedResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            'id':
              type: integer
              format: int32
        meta: { type: object }
        links: { type: object }
