openapi: 3.0.3
info:
  title: 'obmp_cm_lingue API'
  version: 1.0.0
paths:
  /api/v1/obmp_cm_lingue:
    get:
      summary: 'Elenco obmp_cm_lingue'
      parameters:
        - name: page
          in: query
          schema: { type: integer, minimum: 1 }
        - name: perPage
          in: query
          schema: { type: integer, minimum: 1, maximum: 100 }
        - name: 'filter[obmp_cm_lingue_id]'
          in: query
          schema:
            type: integer
            format: int32
        - name: 'filter[obmp_cm_rooms_id]'
          in: query
          schema:
            type: integer
            format: int32
        - name: sort
          in: query
          schema: { type: string, enum: ['obmp_cm_lingue_id', 'obmp_cm_rooms_id'] }
        - name: direction
          in: query
          schema: { type: string, enum: [asc, desc] }
      responses:
        '200':
          description: Elenco paginato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObmpCmLingueListResponse'
    post:
      summary: Crea record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObmpCmLingueCreate'
      responses:
        '201':
          description: Record creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObmpCmLingueCreatedResponse'
        '422': { description: Errore di validazione }
  /api/v1/obmp_cm_lingue/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      summary: Dettaglio record
      responses:
        '200':
          description: Record trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ObmpCmLingueRead'
        '404': { description: Record non trovato }
    put:
      summary: Aggiornamento completo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObmpCmLingueUpdate'
      responses:
        '200': { description: Record aggiornato }
        '422': { description: Errore di validazione }
    patch:
      summary: Aggiornamento parziale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObmpCmLinguePatch'
      responses:
        '200': { description: Record aggiornato }
        '422': { description: Errore di validazione }
    delete:
      summary: Elimina record
      responses:
        '204': { description: Record eliminato }
components:
  schemas:
    ObmpCmLingueRead:
      type: object
      properties:
        'obmp_cm_lingue_id':
          type: integer
          format: int32
        'obmp_cm_rooms_id':
          type: integer
          format: int32
        'hotel_id':
          type: integer
          format: int32
        'obmp_cm_lingue_codice':
          type: string
          nullable: true
          maxLength: 10
        'obmp_cm_lingue_nome':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_descrizione':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_html1':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html2':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html3':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_note':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_politiche':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_condizioni':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_utente_id':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_rooms_obmp_cm_rooms_room_note':
          type: string
          nullable: true
    ObmpCmLingueCreate:
      type: object
      required:
        - 'obmp_cm_rooms_id'
        - 'hotel_id'
      properties:
        'obmp_cm_rooms_id':
          type: integer
          format: int32
        'hotel_id':
          type: integer
          format: int32
        'obmp_cm_lingue_codice':
          type: string
          nullable: true
          maxLength: 10
        'obmp_cm_lingue_nome':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_descrizione':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_html1':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html2':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html3':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_note':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_politiche':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_condizioni':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_utente_id':
          type: string
          nullable: true
          maxLength: 250
    ObmpCmLingueUpdate:
      type: object
      required:
        - 'obmp_cm_rooms_id'
        - 'hotel_id'
      properties:
        'obmp_cm_rooms_id':
          type: integer
          format: int32
        'hotel_id':
          type: integer
          format: int32
        'obmp_cm_lingue_codice':
          type: string
          nullable: true
          maxLength: 10
        'obmp_cm_lingue_nome':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_descrizione':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_html1':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html2':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html3':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_note':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_politiche':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_condizioni':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_utente_id':
          type: string
          nullable: true
          maxLength: 250
    ObmpCmLinguePatch:
      type: object
      properties:
        'obmp_cm_rooms_id':
          type: integer
          format: int32
        'hotel_id':
          type: integer
          format: int32
        'obmp_cm_lingue_codice':
          type: string
          nullable: true
          maxLength: 10
        'obmp_cm_lingue_nome':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_descrizione':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_html1':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html2':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_html3':
          type: string
          nullable: true
          maxLength: 4294967295
        'obmp_cm_lingue_note':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_politiche':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_condizioni':
          type: string
          nullable: true
          maxLength: 250
        'obmp_cm_lingue_utente_id':
          type: string
          nullable: true
          maxLength: 250
    ObmpCmLingueListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ObmpCmLingueRead'
        meta: { type: object }
        links: { type: object }
    ObmpCmLingueCreatedResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            'obmp_cm_lingue_id':
              type: integer
              format: int32
        meta: { type: object }
        links: { type: object }
