<?php

declare(strict_types=1);

namespace App\Controllers\Api\V1;

use App\API\Resources\ActorResource;
use App\Controllers\Api\BaseApiController;
use App\Models\ActorModel;
use App\Services\ActorService;
use App\Validation\ActorApiRules;
use RuntimeException;
use Throwable;

/**
 * REST API v1 for resource `actor`.
 * Exposed operations follow capabilities generated by the Builder/schema.
 * READ operations use the generated Model; WRITE operations use the generated Service.
 * This controller never composes SQL or resolves relation classes dynamically.
 */
final class ActorApiController extends BaseApiController
{
    /** Fields accepted as REST list filters. API query policy belongs to the HTTP boundary. */
    private const FILTERABLE_FIELDS = array (
  0 => 'actor_id',
  1 => 'last_name',
);

    /** Fields accepted for REST list sorting. API query policy belongs to the HTTP boundary. */
    private const SORTABLE_FIELDS = array (
  0 => 'actor_id',
  1 => 'last_name',
);

    /** Fields accepted from REST JSON/form request bodies. Binary upload fields are intentionally excluded. */
    private const WRITABLE_FIELDS = array (
  0 => 'first_name',
  1 => 'last_name',
);

    public function __construct(
        private readonly ActorModel $model = new ActorModel(),
        private readonly ActorService $service = new ActorService()
    ) {
    }

    public function index()
    {
        try {
            $query = (array) $this->request->getGet();
            $query['perPage'] = $this->safePerPage();
            $result = $this->model->apiList($query, self::FILTERABLE_FIELDS, self::SORTABLE_FIELDS);
            return $this->success(ActorResource::collection($result['rows']), $result['meta'], $result['links']);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function show(int|string $id)
    {
        try {
            return $this->success(ActorResource::make($this->recordOrFail($id)));
        } catch (RuntimeException) {
            return $this->error('NOT_FOUND', 'Record not found.', 404);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function create()
    {
        $data = $this->writableData($this->payload());

        if ($data === []) {
            return $this->error('EMPTY_PAYLOAD', 'No writable field received.', 422);
        }
        if (!$this->validateData($data, ActorApiRules::createRules(), ActorApiRules::messages())) {
            return $this->error('VALIDATION_ERROR', 'Dati non validi.', 422, $this->validator->getErrors());
        }
        try {
            $id = $this->service->create($data);

            return $this->success(['actor_id' => $id], [], [], 201);
        } catch (RuntimeException $e) {
            return $this->error('CREATE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function update(int|string $id)
    {
        return $this->writeUpdate($id, false);
    }

    public function patch(int|string $id)
    {
        return $this->writeUpdate($id, true);
    }

    private function writeUpdate(int|string $id, bool $partial)
    {
        $data = $this->writableData($this->payload());
        unset($data['actor_id']);
        if ($data === []) {
            return $this->error('EMPTY_PAYLOAD', 'No writable field received.', 422);
        }
        $rules = ActorApiRules::updateRules($id);
        if ($partial) {
            $rules = array_intersect_key($rules, $data);
        }
        if ($rules !== [] && !$this->validateData($data, $rules, ActorApiRules::messages())) {
            return $this->error('VALIDATION_ERROR', 'Dati non validi.', 422, $this->validator->getErrors());
        }
        try {
            $this->recordOrFail($id);
            if ($partial) {
                $this->service->patch($id, $data);
            } else {
                $this->service->update($id, $data);
            }
            return $this->success(ActorResource::make($this->recordOrFail($id)));
        } catch (RuntimeException $e) {
            if ($e->getMessage() === 'Record not found.') {
                return $this->error('NOT_FOUND', 'Record not found.', 404);
            }
            return $this->error('UPDATE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function delete(int|string $id)
    {
        try {
            $this->recordOrFail($id);
            $this->service->delete($id);
            return $this->response->setStatusCode(204)->setBody('');
        } catch (RuntimeException $e) {
            if ($e->getMessage() === 'Record not found.') {
                return $this->error('NOT_FOUND', 'Record not found.', 404);
            }
            return $this->error('DELETE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }

    /**
     * Filters an incoming REST payload against the generated API write whitelist.
     *
     * Input filtering belongs to the API boundary. The Resource remains an
     * output-only serializer and never performs persistence or request handling.
     *
     * @param array<string,mixed> $data
     * @return array<string,mixed>
     */
    private function writableData(array $data): array
    {
        return array_intersect_key($data, array_flip(self::WRITABLE_FIELDS));
    }

    /**
     * Reads one record through the Model and translates absence into the API
     * application exception used by the existing error mapping.
     */
    private function recordOrFail(int|string $id): object
    {
        $record = $this->model->getDetail($id);
        if (!is_object($record)) {
            throw new RuntimeException('Record not found.');
        }

        return $record;
    }
}
