<?php

declare(strict_types=1);

namespace App\Controllers\Api\V1;

use App\API\Resources\FilmActorResource;
use App\Controllers\Api\BaseApiController;
use App\Models\FilmActorModel;
use App\Services\FilmActorService;
use App\Validation\FilmActorApiRules;
use RuntimeException;
use Throwable;

/**
 * REST API v1 for resource `film_actor`.
 * Exposed operations follow capabilities generated by the Builder/schema.
 * READ operations use the generated Model; WRITE operations use the generated Service.
 * This controller never composes SQL or resolves relation classes dynamically.
 */
final class FilmActorApiController extends BaseApiController
{
    /** Fields accepted as REST list filters. API query policy belongs to the HTTP boundary. */
    private const FILTERABLE_FIELDS = array (
  0 => 'actor_id',
  1 => 'film_id',
);

    /** Fields accepted for REST list sorting. API query policy belongs to the HTTP boundary. */
    private const SORTABLE_FIELDS = array (
  0 => 'actor_id',
  1 => 'film_id',
);

    /** Fields accepted from REST JSON/form request bodies. Binary upload fields are intentionally excluded. */
    private const WRITABLE_FIELDS = array (
  0 => 'actor_id',
  1 => 'film_id',
);

    public function __construct(
        private readonly FilmActorModel $model = new FilmActorModel(),
        private readonly FilmActorService $service = new FilmActorService()
    ) {
    }

    public function index()
    {
        try {
            $query = (array) $this->request->getGet();
            $query['perPage'] = $this->safePerPage();
            $result = $this->model->apiList($query, self::FILTERABLE_FIELDS, self::SORTABLE_FIELDS);
            return $this->success(FilmActorResource::collection($result['rows']), $result['meta'], $result['links']);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function create()
    {
        $data = $this->writableData($this->payload());

        if ($data === []) {
            return $this->error('EMPTY_PAYLOAD', 'No writable field received.', 422);
        }
        if (!$this->validateData($data, FilmActorApiRules::createRules(), FilmActorApiRules::messages())) {
            return $this->error('VALIDATION_ERROR', 'Dati non validi.', 422, $this->validator->getErrors());
        }
        try {
            $id = $this->service->create($data);

            return $this->success(['actor_id' => $id], [], [], 201);
        } catch (RuntimeException $e) {
            return $this->error('CREATE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }

    /**
     * Filters an incoming REST payload against the generated API write whitelist.
     *
     * Input filtering belongs to the API boundary. The Resource remains an
     * output-only serializer and never performs persistence or request handling.
     *
     * @param array<string,mixed> $data
     * @return array<string,mixed>
     */
    private function writableData(array $data): array
    {
        return array_intersect_key($data, array_flip(self::WRITABLE_FIELDS));
    }
}
