<?php

declare(strict_types=1);

namespace App\Controllers\Api\V1;

use App\API\Resources\FilmResource;
use App\Controllers\Api\BaseApiController;
use App\Libraries\Crud\CrudUploadManager;
use App\Models\FilmModel;
use App\Services\FilmService;
use App\Validation\FilmApiRules;
use RuntimeException;
use Throwable;

/**
 * REST API v1 for resource `film`.
 * Exposed operations follow capabilities generated by the Builder/schema.
 * READ operations use the generated Model; WRITE operations use the generated Service.
 * This controller never composes SQL or resolves relation classes dynamically.
 */
final class FilmApiController extends BaseApiController
{
    private const API_TABLE = 'film';
    private const UPLOAD_FIELDS = array (
  'uploads' =>
  array (
    'type' => 'file',
    'required' => false,
  ),
);
    /** Fields accepted as REST list filters. API query policy belongs to the HTTP boundary. */
    private const FILTERABLE_FIELDS = array (
  0 => 'film_id',
  1 => 'title',
  2 => 'language_id',
  3 => 'original_language_id',
);

    /** Fields accepted for REST list sorting. API query policy belongs to the HTTP boundary. */
    private const SORTABLE_FIELDS = array (
  0 => 'film_id',
  1 => 'title',
  2 => 'language_id',
  3 => 'original_language_id',
);

    /** Fields accepted from REST JSON/form request bodies. Binary upload fields are intentionally excluded. */
    private const WRITABLE_FIELDS = array (
  0 => 'title',
  1 => 'description',
  2 => 'release_year',
  3 => 'language_id',
  4 => 'original_language_id',
  5 => 'rental_duration',
  6 => 'rental_rate',
  7 => 'length',
  8 => 'replacement_cost',
  9 => 'rating',
  10 => 'special_features',
);

    private CrudUploadManager $uploadManager;
    public function __construct(
        private readonly FilmModel $model = new FilmModel(),
        private readonly FilmService $service = new FilmService()
    ) {
        $this->uploadManager = new CrudUploadManager();
    }

    public function index()
    {
        try {
            $query = (array) $this->request->getGet();
            $query['perPage'] = $this->safePerPage();
            $result = $this->model->apiList($query, self::FILTERABLE_FIELDS, self::SORTABLE_FIELDS);
            return $this->success(FilmResource::collection($result['rows']), $result['meta'], $result['links']);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function show(int|string $id)
    {
        try {
            return $this->success(FilmResource::make($this->recordOrFail($id)));
        } catch (RuntimeException) {
            return $this->error('NOT_FOUND', 'Record not found.', 404);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function create()
    {
        $data = $this->writableData($this->payload());
        $uploadErrors = $this->apiUploadErrors(false);
        if ($uploadErrors !== []) {
            return $this->error('VALIDATION_ERROR', 'Upload non valido.', 422, $uploadErrors);
        }
        if ($data === [] && !$this->hasApiUpload()) {
            return $this->error('EMPTY_PAYLOAD', 'No writable field received.', 422);
        }
        if (!$this->validateData($data, FilmApiRules::createRules(), FilmApiRules::messages())) {
            return $this->error('VALIDATION_ERROR', 'Dati non validi.', 422, $this->validator->getErrors());
        }
        try {
            $id = $this->service->create($data);
            $uploadData = $this->storeApiUploads($id);
            if ($uploadData !== []) {
                $this->service->updateUploads($id, $uploadData);
            }
            return $this->success(['film_id' => $id], [], [], 201);
        } catch (RuntimeException $e) {
            return $this->error('CREATE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function update(int|string $id)
    {
        return $this->writeUpdate($id, false);
    }

    public function patch(int|string $id)
    {
        return $this->writeUpdate($id, true);
    }

    private function writeUpdate(int|string $id, bool $partial)
    {
        $data = $this->writableData($this->payload());
        unset($data['film_id']);
        if ($data === []) {
            return $this->error('EMPTY_PAYLOAD', 'No writable field received.', 422);
        }
        $rules = FilmApiRules::updateRules($id);
        if ($partial) {
            $rules = array_intersect_key($rules, $data);
        }
        if ($rules !== [] && !$this->validateData($data, $rules, FilmApiRules::messages())) {
            return $this->error('VALIDATION_ERROR', 'Dati non validi.', 422, $this->validator->getErrors());
        }
        try {
            $this->recordOrFail($id);
            if ($partial) {
                $this->service->patch($id, $data);
            } else {
                $this->service->update($id, $data);
            }
            return $this->success(FilmResource::make($this->recordOrFail($id)));
        } catch (RuntimeException $e) {
            if ($e->getMessage() === 'Record not found.') {
                return $this->error('NOT_FOUND', 'Record not found.', 404);
            }
            return $this->error('UPDATE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    /**
     * Replaces one or more upload fields through multipart/form-data POST.
     *
     * Separate endpoint from PUT/PATCH for PHP 8.3 compatibility, where
     * $_FILES viene popolato automaticamente per multipart POST.
     */
    public function upload(int|string $id)
    {
        $uploadErrors = $this->apiUploadErrors(true);
        if ($uploadErrors !== []) {
            return $this->error('VALIDATION_ERROR', 'Upload non valido.', 422, $uploadErrors);
        }
        if (!$this->hasApiUpload()) {
            return $this->error('EMPTY_UPLOAD', 'No file ricevuto.', 422);
        }

        try {
            $this->recordOrFail($id);
            $oldUploadValues = $this->currentApiUploadValues($id);
            $uploadData = $this->storeApiUploads($id);
            if ($uploadData === []) {
                return $this->error('EMPTY_UPLOAD', 'No file valido ricevuto.', 422);
            }

            $this->service->updateUploads($id, $uploadData);
            $this->deleteReplacedApiUploads($oldUploadValues, $uploadData);

            return $this->success(FilmResource::make($this->recordOrFail($id)));
        } catch (RuntimeException $e) {
            if ($e->getMessage() === 'Record not found.') {
                return $this->error('NOT_FOUND', 'Record not found.', 404);
            }
            return $this->error('UPLOAD_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }
    public function delete(int|string $id)
    {
        try {
            $this->recordOrFail($id);
            $this->service->delete($id);
            return $this->response->setStatusCode(204)->setBody('');
        } catch (RuntimeException $e) {
            if ($e->getMessage() === 'Record not found.') {
                return $this->error('NOT_FOUND', 'Record not found.', 404);
            }
            return $this->error('DELETE_FAILED', $e->getMessage(), 400);
        } catch (Throwable $e) {
            return $this->internalError($e);
        }
    }

    /**
     * Filters an incoming REST payload against the generated API write whitelist.
     *
     * Input filtering belongs to the API boundary. The Resource remains an
     * output-only serializer and never performs persistence or request handling.
     *
     * @param array<string,mixed> $data
     * @return array<string,mixed>
     */
    private function writableData(array $data): array
    {
        return array_intersect_key($data, array_flip(self::WRITABLE_FIELDS));
    }

    /**
     * Reads one record through the Model and translates absence into the API
     * application exception used by the existing error mapping.
     */
    private function recordOrFail(int|string $id): object
    {
        $record = $this->model->getDetail($id);
        if (!is_object($record)) {
            throw new RuntimeException('Record not found.');
        }

        return $record;
    }
    /** @return array<string,string> */
    private function apiUploadErrors(bool $isUpdate): array
    {
        return $this->uploadManager->validate(
            self::UPLOAD_FIELDS,
            $this->request->getFiles(),
            $isUpdate
        );
    }

    private function hasApiUpload(): bool
    {
        foreach (array_keys(self::UPLOAD_FIELDS) as $field) {
            $file = $this->request->getFile($field);
            if ($file !== null && $file->getError() !== UPLOAD_ERR_NO_FILE) {
                return true;
            }
        }

        return false;
    }

    /** @return array<string,string> */
    private function storeApiUploads(int|string $id): array
    {
        return $this->uploadManager->store(
            self::API_TABLE,
            $id,
            self::UPLOAD_FIELDS,
            $this->request->getFiles()
        );
    }

    /** @return array<string,string> */
    private function currentApiUploadValues(int|string $id): array
    {
        if (self::UPLOAD_FIELDS === []) {
            return [];
        }

        $record = $this->recordOrFail($id);
        $values = [];
        foreach (array_keys(self::UPLOAD_FIELDS) as $field) {
            if (is_array($record)) {
                $values[$field] = (string) ($record[$field] ?? '');
            } else {
                $values[$field] = isset($record->{$field}) ? (string) $record->{$field} : '';
            }
        }

        return $values;
    }

    /** @param array<string,string> $old @param array<string,string> $new */
    private function deleteReplacedApiUploads(array $old, array $new): void
    {
        foreach ($new as $field => $filename) {
            $previous = (string) ($old[$field] ?? '');
            if ($previous !== '' && $previous !== $filename) {
                $this->uploadManager->delete($previous);
            }
        }
    }
}
